name: Deploy Infra + React App

on:
  push:
    branches:
      - dev
      - qa
      - stg
      - prd
  pull_request:
    branches: [ dev, qa, stg, prd ]

jobs:

  # code-quality:
  #   name: Code Quality - SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       with:
  #         projectBaseDir: .
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  #         SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

  infra:
    name: Infrastructure 
    runs-on: ubuntu-latest
    needs: code-quality

    env:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Select/Create Workspace
        run: |
          ENV=${GITHUB_REF##*/}
          terraform workspace select $ENV || terraform workspace new $ENV
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra
      
      - name: Get Deployment Token
        run: |
          ENV=${GITHUB_REF##*/}
          TOKEN=$(az staticwebapp secrets list \
            --name webapp-$ENV \
            --resource-group rg-$ENV \
            --query "properties.deploymentToken" -o tsv)
          echo "AZURE_STATIC_WEB_APPS_API_TOKEN=$TOKEN" >> $GITHUB_ENV



  deploy:
    name: Deploy React App
    runs-on: ubuntu-latest
    needs: infra

    env:
      Azure-static-webapp-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy React App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          output_location: "build"
